baseurl = "https://www.firdausng.com/"
languageCode = "en-us"
title = "Firdaus's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "Firdaus"
    site_description = "The blog of Firdaus"
    location = "at beach"
    # Link custom assets relative to /static
    avatar = "img/profile_pic.jpg"
    header_background = "img/keyboard_gee.jpg"
    header_title = "Firdaus's Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = "firdaus-kamaruddin"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "firdausng"
    gplus     = ""
